"""Package-local structural verifier with no generated bytecode."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .model import loads_strict_json
from .paths import is_link_like


REQUIRED_FILES = (
    "README.md",
    "SKILL.md",
    "agents/openai.yaml",
    "harness.package.json",
    "hq.py",
    "orchestration_harness/__init__.py",
    "orchestration_harness/cli.py",
    "orchestration_harness/model.py",
    "orchestration_harness/paths.py",
    "orchestration_harness/render.py",
    "orchestration_harness/service.py",
    "orchestration_harness/transaction.py",
    "orchestration_harness/verifier.py",
    "templates/master/AGENTS.md",
    "templates/master/ARCHITECTURE.md",
    "templates/master/NEXT.md",
    "templates/project/AGENTS.md",
    "templates/project/ARCHITECTURE.md",
    "templates/project/RECORDS.md",
    "templates/project/REFLECTIONS.md",
    "templates/project/SESSIONS.md",
)


def verify_package(package_root: Path | None = None) -> list[str]:
    root = (
        Path(package_root)
        if package_root is not None
        else Path(__file__).resolve().parents[1]
    )
    issues: list[str] = []
    for relative in REQUIRED_FILES:
        path = root / relative
        if is_link_like(path) or not path.is_file():
            issues.append(f"MISSING:{relative}")

    for path in root.rglob("*"):
        if is_link_like(path):
            issues.append(f"SYMLINK:{path.relative_to(root).as_posix()}")
            continue
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            issues.append(f"UTF8:{path.relative_to(root).as_posix()}")
            continue
        if path.suffix == ".py":
            try:
                compile(text, path.name, "exec")
            except SyntaxError:
                issues.append(f"PYTHON:{path.relative_to(root).as_posix()}")

    manifest_path = root / "harness.package.json"
    if manifest_path.is_file() and not is_link_like(manifest_path):
        try:
            manifest: Any = loads_strict_json(
                manifest_path.read_text(encoding="utf-8")
            )
        except Exception:
            issues.append("MANIFEST:invalid")
        else:
            expected = {
                "id": "orchestration",
                "license": "MIT",
                "status": "implemented",
                "version": "0.1.0",
            }
            if not isinstance(manifest, dict) or any(
                manifest.get(key) != value for key, value in expected.items()
            ):
                issues.append("MANIFEST:contract")

    skill_path = root / "SKILL.md"
    if skill_path.is_file() and not is_link_like(skill_path):
        try:
            skill_text = skill_path.read_text(encoding="utf-8")
            opening, separator, _body = skill_text.partition("\n---\n")
            if not separator or not opening.startswith("---\n"):
                raise ValueError
            metadata: dict[str, str] = {}
            for line in opening.removeprefix("---\n").splitlines():
                key, marker, value = line.partition(":")
                if not marker or not value.strip():
                    raise ValueError
                metadata[key.strip()] = value.strip()
            if frozenset(metadata) != frozenset(("name", "description")):
                raise ValueError
            if metadata["name"] != "orchestration":
                raise ValueError
        except (OSError, UnicodeError, ValueError):
            issues.append("SKILL:frontmatter")

    agents_path = root / "agents" / "openai.yaml"
    if agents_path.is_file() and not is_link_like(agents_path):
        try:
            agents_text = agents_path.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            issues.append("SKILL:agents")
        else:
            required_values = (
                'display_name: "Orchestration Harness"',
                'short_description: "Run safe local Master and front workflows"',
                "default_prompt:",
                "$orchestration",
            )
            if not all(value in agents_text for value in required_values):
                issues.append("SKILL:agents")
    return sorted(set(issues))
