"""Package-local structural verifier with no generated bytecode."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .model import loads_strict_json
from .paths import is_link_like


REQUIRED_FILES = (
    "README.md",
    "README.pt-BR.md",
    "OPERATOR_GUIDE.md",
    "OPERATOR_GUIDE.pt-BR.md",
    "operations.json",
    "harness.package.json",
    "hq.py",
    "orchestration_harness/__init__.py",
    "orchestration_harness/cli.py",
    "orchestration_harness/model.py",
    "orchestration_harness/paths.py",
    "orchestration_harness/render.py",
    "orchestration_harness/service.py",
    "orchestration_harness/transaction.py",
    "orchestration_harness/verifier.py",
    "templates/master/AGENTS.md",
    "templates/master/ARCHITECTURE.md",
    "templates/master/NEXT.md",
    "templates/project/AGENTS.md",
    "templates/project/ARCHITECTURE.md",
    "templates/project/RECORDS.md",
    "templates/project/REFLECTIONS.md",
    "templates/project/SESSIONS.md",
)


def verify_package(package_root: Path | None = None) -> list[str]:
    root = (
        Path(package_root)
        if package_root is not None
        else Path(__file__).resolve().parents[1]
    )
    issues: list[str] = []
    for relative in REQUIRED_FILES:
        path = root / relative
        if is_link_like(path) or not path.is_file():
            issues.append(f"MISSING:{relative}")

    for path in root.rglob("*"):
        if is_link_like(path):
            issues.append(f"SYMLINK:{path.relative_to(root).as_posix()}")
            continue
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            issues.append(f"UTF8:{path.relative_to(root).as_posix()}")
            continue
        if path.suffix == ".py":
            try:
                compile(text, path.name, "exec")
            except SyntaxError:
                issues.append(f"PYTHON:{path.relative_to(root).as_posix()}")

    manifest_path = root / "harness.package.json"
    if manifest_path.is_file() and not is_link_like(manifest_path):
        try:
            manifest: Any = loads_strict_json(
                manifest_path.read_text(encoding="utf-8")
            )
        except Exception:
            issues.append("MANIFEST:invalid")
        else:
            expected = {
                "id": "orchestration",
                "license": "MIT",
                "status": "implemented",
                "version": "0.2.1",
            }
            if not isinstance(manifest, dict) or any(
                manifest.get(key) != value for key, value in expected.items()
            ):
                issues.append("MANIFEST:contract")

    return sorted(set(issues))
